# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Dependencies
markdown:         kramdown

# Setup
title:               'J.<br>Bradley<br>Eustice'
tagline:             'Ph.D. Candidate [Economics], M.S. [Statistics]'
description:         'Ph.D. Candidate [Economics];<br> M.S. [Statistics];<br> Adjunct Faculty BYU'
url:                 http://jbradleyeustice.com
baseurl:             '/'
paginate:            10

# About/contact
author:
  name:              J. Bradley Eustice
  url:               http://jbradleyeustice.com
  email:             jbradleyeustice@gmail.com

github:
  repo:           https://github.com/jbeustice/mySite
